### ISSUE TITLE
Prepare DB connector for additional backends besides Cassandra

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-REST#39]

**Comment by myrho** [comment]
There now is the package `gsrest.db` which may contain DB specific implementations for fetching data. DB Driver can be set in `instance/config.yaml`:

```yaml
database:
   driver: cassandra
   # database specific config fields
```
